---
resources:
- name: sandbox
  type: git
  source:
    uri: https://github.com/vspiewak/concourse-ci-sandbox.git

jobs:
- name: job-test
  public: true
  plan:
  - get: sandbox
    trigger: true
  - task: test
    file: sandbox/task_test.yml
